const $=selector=>document.querySelector(selector);
const state={me:null,file:null,uploading:false,jobs:[],selectedJob:null,page:1,pageSize:100,poll:null};
function bytes(value){if(!Number.isFinite(value))return '—';const units=['B','KiB','MiB','GiB'];let size=value,index=0;while(size>=1024&&index<units.length-1){size/=1024;index++}return `${size.toFixed(index?1:0)} ${units[index]}`}
function date(value){return value?new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value*1000)):'—'}
function notify(message){const toast=$('#toast');toast.textContent=message;toast.classList.remove('hidden');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.add('hidden'),6000)}
async function request(url,options={}){const response=await fetch(url,{cache:'no-store',...options});let value={};try{value=await response.json()}catch{}if(!response.ok)throw new Error(value.error||`请求失败（${response.status}）`);return value}
async function digest(blob){const value=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return [...new Uint8Array(value)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function selectFile(file){$('#uploadError').classList.add('hidden');if(!file){state.file=null;$('#selectedFile').classList.add('hidden');$('#uploadButton').disabled=true;return}if(!file.name.toLowerCase().endsWith('.visionproj')){showUploadError('只允许上传 .visionproj 文件');return}if(state.me&&file.size>state.me.max_upload_size){showUploadError(`文件超过 ${bytes(state.me.max_upload_size)} 上限`);return}state.file=file;const box=$('#selectedFile');box.replaceChildren(document.createTextNode(file.name));const size=document.createElement('span');size.textContent=bytes(file.size);box.append(size);box.classList.remove('hidden');$('#uploadButton').disabled=state.uploading}
function showUploadError(message){const box=$('#uploadError');box.textContent=message;box.classList.remove('hidden');$('#uploadButton').disabled=true}
function uploadProgress(percent,message){$('#uploadProgress').classList.remove('hidden');$('#uploadBar').value=percent;$('#uploadPercent').textContent=`${Math.round(percent)}%`;$('#uploadMessage').textContent=message}
async function upload(){if(!state.file||state.uploading)return;state.uploading=true;$('#uploadButton').disabled=true;$('#fileInput').disabled=true;$('#uploadError').classList.add('hidden');const file=state.file;try{const chunkSize=state.me.chunk_size;const chunkCount=Math.ceil(file.size/chunkSize);const created=await request('/api/uploads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,total_size:file.size,chunk_count:chunkCount})});for(let index=0;index<chunkCount;index++){const chunk=file.slice(index*chunkSize,Math.min(file.size,(index+1)*chunkSize));uploadProgress(index/chunkCount*100,`正在上传第 ${index+1} / ${chunkCount} 块`);const hash=await digest(chunk);await request(`/api/uploads/${created.id}/chunks/${index}`,{method:'PUT',headers:{'Content-Type':'application/octet-stream','X-Chunk-SHA256':hash},body:chunk})}uploadProgress(100,'正在校验项目并加入分析队列');await request(`/api/uploads/${created.id}/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});notify('上传完成，已进入本机 GPU 分析队列');state.file=null;$('#fileInput').value='';$('#selectedFile').classList.add('hidden');await refreshJobs()}catch(error){showUploadError(error.message)}finally{state.uploading=false;$('#fileInput').disabled=false;$('#uploadButton').disabled=!state.file;setTimeout(()=>$('#uploadProgress').classList.add('hidden'),1200)}}
const stateNames={uploading:'上传中',validating:'校验中',queued:'排队中',running:'分析中',completed:'已完成',failed:'失败'};
function jobElement(job){const root=document.createElement('article');root.className='job';const top=document.createElement('div');top.className='job-top';const name=document.createElement('div');name.className='job-name';name.title=job.filename;name.textContent=job.filename;const badge=document.createElement('span');badge.className=`job-state ${job.state}`;badge.textContent=stateNames[job.state]||job.state;top.append(name,badge);root.append(top);const message=document.createElement('p');message.className='job-message';message.textContent=`${job.message||''} · ${date(job.created_at)}`;root.append(message);if(['queued','running','uploading','validating'].includes(job.state)){const progress=document.createElement('progress');progress.max=100;progress.value=Math.round((job.progress||0)*100);root.append(progress)}if(job.error){const error=document.createElement('p');error.className='error';error.textContent=job.error;root.append(error)}const actions=document.createElement('div');actions.className='job-actions';if(job.result_ready){const view=document.createElement('button');view.type='button';view.className='ghost';view.textContent='查看结果';view.addEventListener('click',()=>loadResults(job.id,1));actions.append(view)}if(!['running','validating'].includes(job.state)){const remove=document.createElement('button');remove.type='button';remove.className='danger';remove.textContent='删除';remove.addEventListener('click',()=>deleteJob(job));actions.append(remove)}root.append(actions);return root}
function renderJobs(){const box=$('#jobs');box.replaceChildren();if(!state.jobs.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='还没有任务';box.append(empty);return}state.jobs.forEach(job=>box.append(jobElement(job)))}
async function refreshJobs(){try{const value=await request('/api/jobs');state.jobs=value.jobs;renderJobs();const active=state.jobs.some(job=>['uploading','validating','queued','running'].includes(job.state));clearTimeout(state.poll);if(active)state.poll=setTimeout(refreshJobs,2500)}catch(error){notify(error.message)}}
async function deleteJob(job){if(!confirm(`删除任务“${job.filename}”及其本机数据？`))return;try{await request(`/api/jobs/${job.id}`,{method:'DELETE'});if(state.selectedJob===job.id)clearResults();await refreshJobs()}catch(error){notify(error.message)}}
function clearResults(){state.selectedJob=null;state.page=1;$('#resultSummary').classList.add('hidden');$('#resultCount').textContent='';$('#pagination').classList.add('hidden');const box=$('#results');box.replaceChildren();const empty=document.createElement('div');empty.className='empty-state';const mark=document.createElement('span');mark.textContent='◇';const title=document.createElement('strong');title.textContent='结果将在这里显示';const text=document.createElement('p');text.textContent='分析完成后，从左侧任务中选择“查看结果”。';empty.append(mark,title,text);box.append(empty)}
function resultCard(item){const card=document.createElement('article');card.className='result';const image=document.createElement('img');image.className='result-image';image.loading='lazy';image.alt=`${item.relative_path} 的标注预览`;image.src=item.preview_url;card.append(image);const body=document.createElement('div');body.className='result-body';const row=document.createElement('div');row.className='score-row';const label=document.createElement('strong');label.textContent='疑似分错';const score=document.createElement('span');score.className='score';score.textContent=Number(item.suspicion_score).toFixed(1);row.append(label,score);const path=document.createElement('p');path.className='path';path.title=item.relative_path;path.textContent=item.relative_path;const flow=document.createElement('div');flow.className='label-flow';const original=document.createElement('span');original.textContent=item.original_label;const arrow=document.createElement('b');arrow.textContent='→';const suggested=document.createElement('span');suggested.textContent=item.suggested_label||'—';flow.append(original,arrow,suggested);const metrics=document.createElement('p');metrics.className='metrics';metrics.textContent=`原类别支持 ${Math.round((item.label_confidence||0)*100)}% · 邻域支持 ${Math.round((item.neighbor_support||0)*100)}%`;body.append(row,path,flow,metrics);card.append(body);return card}
function renderSummary(summary){const box=$('#resultSummary');box.replaceChildren();const values=[`${summary.item_count} 个复查项`,`${summary.classes.length} 个类别`,`${summary.device==='cuda'?'GPU':'CPU'} · ${summary.dtype||'—'}`,`${summary.effective_projection||'—'} 投影`,summary.cache_hit?'已使用缓存':'新分析'];for(const value of values){const span=document.createElement('span');span.textContent=value;box.append(span)}box.classList.remove('hidden')}
async function loadResults(jobId,page){try{const value=await request(`/api/jobs/${jobId}/results?page=${page}&limit=${state.pageSize}`);state.selectedJob=jobId;state.page=page;renderSummary(value.summary);$('#resultCount').textContent=`按疑似度排序 · ${value.summary.item_count} 项`;const box=$('#results');box.replaceChildren();value.items.forEach(item=>box.append(resultCard(item)));const pages=Math.max(1,Math.ceil(value.summary.item_count/state.pageSize));$('#pageLabel').textContent=`第 ${page} / ${pages} 页`;$('#previousPage').disabled=page<=1;$('#nextPage').disabled=page>=pages;$('#pagination').classList.toggle('hidden',pages<=1);if(innerWidth<901)$('.results-card').scrollIntoView({behavior:'smooth',block:'start'})}catch(error){notify(error.message)}}
async function init(){try{state.me=await request('/api/me');$('#identity').textContent=state.me.email;$('#sizeLimit').textContent=bytes(state.me.max_upload_size);await refreshJobs()}catch(error){$('#identity').textContent='身份验证失败';showUploadError(error.message)}}
$('#fileInput').addEventListener('change',event=>selectFile(event.target.files[0]));$('#uploadButton').addEventListener('click',upload);$('#refreshButton').addEventListener('click',refreshJobs);$('#previousPage').addEventListener('click',()=>state.selectedJob&&loadResults(state.selectedJob,state.page-1));$('#nextPage').addEventListener('click',()=>state.selectedJob&&loadResults(state.selectedJob,state.page+1));for(const name of ['dragenter','dragover'])$('#dropzone').addEventListener(name,event=>{event.preventDefault();if(!state.uploading)$('#dropzone').classList.add('dragging')});for(const name of ['dragleave','drop'])$('#dropzone').addEventListener(name,event=>{event.preventDefault();$('#dropzone').classList.remove('dragging')});$('#dropzone').addEventListener('drop',event=>{if(!state.uploading)selectFile(event.dataTransfer.files[0])});init();
